#!/usr/bin/env python3
"""Generate the non-task-centric V1 Text-to-SQL KG as idempotent Cypher."""
from __future__ import annotations

import argparse
import hashlib
import json
import re
from pathlib import Path


def cy(value):
    if value is None:
        return "null"
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, (int, float)):
        return str(value)
    if isinstance(value, list):
        return "[" + ", ".join(cy(v) for v in value) + "]"
    return "'" + str(value).replace("\\", "\\\\").replace("'", "\\'").replace("\r", "").replace("\n", "\\n") + "'"


def props(d):
    return "{" + ", ".join(f"{k}: {cy(v)}" for k, v in d.items() if v is not None) + "}"


def norm(s):
    return re.sub(r"[^a-z0-9]+", "_", s.lower()).strip("_")


def full_name(text, fallback):
    m = re.search(r"Full name:\s*['\u2018\u2019\"]([^'\u2018\u2019\"]+)", text, re.I)
    return m.group(1).strip() if m else fallback


def parse_ddl(path):
    text = path.read_text(errors="replace")
    tables, fks = {}, []
    # CREATE blocks end before sample rows; identifiers in this corpus are simple.
    for m in re.finditer(r'CREATE TABLE\s+"?([^"\s(]+)"?\s*\((.*?)\n\);', text, re.I | re.S):
        table, body = m.group(1).lower(), m.group(2)
        cols = []
        for raw in body.splitlines():
            line = raw.strip().rstrip(",")
            if not line or re.match(r"(?:PRIMARY|FOREIGN|UNIQUE|CONSTRAINT)\b", line, re.I):
                continue
            cm = re.match(r'"?([^"\s]+)"?\s+(.+)', line)
            if cm:
                cols.append((cm.group(1).lower(), cm.group(2)))
        tables[table] = cols
        for fm in re.finditer(r'FOREIGN KEY\s*\(\s*"?([^"\s)]+)"?\s*\)\s*REFERENCES\s+"?([^"\s(]+)"?\s*\(\s*"?([^"\s)]+)', body, re.I):
            fks.append((table, fm.group(1).lower(), fm.group(2).lower(), fm.group(3).lower()))
    return tables, fks


def main():
    ap = argparse.ArgumentParser()
    default_source = Path(__file__).resolve().parents[2] / "BIRD-Interact-Claude" / "bird-interact-lite"
    ap.add_argument("--source", type=Path, default=default_source)
    ap.add_argument("--output", type=Path, default=Path(__file__).with_name("mapping.cypher"))
    args = ap.parse_args()
    source = args.source.resolve()
    domains = sorted(p.parent.name for p in source.glob("*/*_kb.jsonl"))
    out = ["// Generated by generate.py; do not edit by hand.", "// Idempotent: nodes/relationships use stable ids.", ""]
    stats = {"domains": 0, "tables": 0, "columns": 0, "knowledge": 0, "dependencies": 0, "attribute_links": 0, "foreign_keys": 0}

    for db in domains:
        stats["domains"] += 1
        folder = source / db
        kb_path = folder / f"{db}_kb.jsonl"
        cm_path = folder / f"{db}_column_meaning_base.json"
        schema_path = folder / f"{db}_schema.txt"
        source_hash = hashlib.sha256(kb_path.read_bytes()).hexdigest()
        domain_id = f"domain:{db}"
        out.append(f"MERGE (d:Concept {{id: {cy(domain_id)}}}) SET d += {props({'name': db, 'concept_kind': 'domain', 'domain': db, 'source_hash': source_hash})};")

        meanings = json.loads(cm_path.read_text()) if cm_path.exists() else {}
        meaning_idx = {}
        for key, desc in meanings.items():
            parts = key.split("|")
            if len(parts) < 3:
                continue
            keydb, table, column = parts[0], parts[1].lower(), "|".join(parts[2:]).lower()
            # cross_db documentation uses the historical namespace "cross".
            if keydb not in (db, "cross" if db == "cross_db" else db):
                continue
            if not isinstance(desc, str):
                desc = json.dumps(desc, ensure_ascii=False, sort_keys=True)
            meaning_idx[(table, column)] = (full_name(desc, column), desc)

        tables, fks = parse_ddl(schema_path)
        col_lookup = {}
        for table, columns in sorted(tables.items()):
            stats["tables"] += 1
            entity_name = re.sub(r"[_-]+", " ", table).strip().title()
            entity_id = f"entity:{db}:{norm(table)}"
            pt_id = f"physical:{db}:table:{table}"
            out += [
                f"MERGE (e:LogicalEntity {{id: {cy(entity_id)}}}) SET e += {props({'name': entity_name, 'domain': db, 'mapping_status': 'ddl_asserted'})};",
                f"MERGE (p:PhysicalSchemaItem {{id: {cy(pt_id)}}}) SET p += {props({'name': table, 'kind': 'table', 'database': db, 'table': table, 'source_file': str(schema_path.relative_to(source))})};",
                f"MATCH (p:PhysicalSchemaItem {{id:{cy(pt_id)}}}), (e:LogicalEntity {{id:{cy(entity_id)}}}) MERGE (p)-[:IMPLEMENTS {{id:{cy(pt_id+'->'+entity_id)}}}]->(e);",
                f"MATCH (e:LogicalEntity {{id:{cy(entity_id)}}}), (d:Concept {{id:{cy(domain_id)}}}) MERGE (e)-[:VALID_IN_DOMAIN {{id:{cy(entity_id+'->'+domain_id)}}}]->(d);",
            ]
            for column, ddl_type in columns:
                stats["columns"] += 1
                label, desc = meaning_idx.get((table, column), (column, None))
                attr_id = f"attribute:{db}:{norm(table)}:{norm(column)}"
                pc_id = f"physical:{db}:column:{table}.{column}"
                col_lookup.setdefault(column, []).append(attr_id)
                out += [
                    f"MERGE (a:LogicalAttribute {{id:{cy(attr_id)}}}) SET a += {props({'name': label, 'domain': db, 'entity_id': entity_id, 'description': desc, 'mapping_status': 'documented' if desc else 'ddl_only'})};",
                    f"MERGE (p:PhysicalSchemaItem {{id:{cy(pc_id)}}}) SET p += {props({'name': column, 'kind': 'column', 'database': db, 'table': table, 'column': column, 'ddl_type': ddl_type})};",
                    f"MATCH (e:LogicalEntity {{id:{cy(entity_id)}}}), (a:LogicalAttribute {{id:{cy(attr_id)}}}) MERGE (e)-[:HAS_ATTRIBUTE {{id:{cy(entity_id+'->'+attr_id)}}}]->(a);",
                    f"MATCH (p:PhysicalSchemaItem {{id:{cy(pc_id)}}}), (a:LogicalAttribute {{id:{cy(attr_id)}}}) MERGE (p)-[:IMPLEMENTS {{id:{cy(pc_id+'->'+attr_id)}}}]->(a);",
                ]

        for ft, fc, tt, tc in sorted(fks):
            if ft not in tables or tt not in tables:
                continue
            stats["foreign_keys"] += 1
            left, right = f"physical:{db}:column:{ft}.{fc}", f"physical:{db}:column:{tt}.{tc}"
            rid = f"fk:{db}:{ft}.{fc}->{tt}.{tc}"
            out.append(f"MATCH (a:PhysicalSchemaItem {{id:{cy(left)}}}), (b:PhysicalSchemaItem {{id:{cy(right)}}}) MERGE (a)-[r:JOINABLE_VIA {{id:{cy(rid)}}}]->(b) SET r.predicate={cy(ft+'.'+fc+' = '+tt+'.'+tc)}, r.kind='foreign_key';")
            left_table, right_table = f"physical:{db}:table:{ft}", f"physical:{db}:table:{tt}"
            table_rid = f"fk-table:{db}:{ft}.{fc}->{tt}.{tc}"
            out.append(f"MATCH (a:PhysicalSchemaItem {{id:{cy(left_table)}}}), (b:PhysicalSchemaItem {{id:{cy(right_table)}}}) MERGE (a)-[r:JOINABLE_VIA {{id:{cy(table_rid)}}}]->(b) SET r.predicate={cy(ft+'.'+fc+' = '+tt+'.'+tc)}, r.kind='foreign_key', r.left_column={cy(fc)}, r.right_column={cy(tc)};")

        knowledge = []
        for line_no, line in enumerate(kb_path.read_text().splitlines(), 1):
            if line.strip():
                k = json.loads(line); k["_line"] = line_no; knowledge.append(k)
        by_id = {k["id"]: k for k in knowledge}
        node_ids = {}
        for k in knowledge:
            stats["knowledge"] += 1
            label = {"calculation_knowledge": "Metric", "domain_knowledge": "Rule", "value_illustration": "Concept"}.get(k.get("type"), "Concept")
            prefix = {"Metric": "metric", "Rule": "rule", "Concept": "concept"}[label]
            kid = f"{prefix}:{db}:kb:{k['id']}"; node_ids[k["id"]] = kid
            definition = k.get("definition", "")
            if label == "Metric":
                pattern = "metric"
                if re.search(r"ratio|/|\\frac", k["knowledge"] + definition, re.I): pattern = "ratio_metric"
                if re.search(r"weighted|composite|index|score", k["knowledge"], re.I): pattern = "composite_metric"
            elif label == "Rule":
                pattern = "temporal_rule" if re.search(r"CURRENT_DATE|NOW\(|day|deadline|overdue", definition, re.I) else ("threshold_or_classification" if re.search(r"[<>]|threshold|considered|classified|category", definition, re.I) else "opaque_rule")
            else: pattern = "categorical_value_or_concept"
            mapping = "unresolved"
            used = []
            for token in sorted(set(re.findall(r"\\text\{([^}]+)\}|\b([A-Z][A-Za-z0-9_]{2,})\b", definition))):
                name = (token[0] or token[1]).lower()
                if len(col_lookup.get(name, [])) == 1:
                    used.append(col_lookup[name][0])
            used = sorted(set(used)); mapping = "exact_identifier" if used else "unresolved"
            nprops = {'name': k['knowledge'], 'description': k.get('description'), 'raw_definition': definition, 'knowledge_type': k.get('type'), 'domain': db, 'source_file': str(kb_path.relative_to(source)), 'source_line': k['_line'], 'source_knowledge_id': k['id'], 'mapping_status': mapping, 'pattern': pattern}
            out.append(f"MERGE (n:{label} {{id:{cy(kid)}}}) SET n += {props(nprops)};")
            out.append(f"MATCH (n:{label} {{id:{cy(kid)}}}), (d:Concept {{id:{cy(domain_id)}}}) MERGE (n)-[:VALID_IN_DOMAIN {{id:{cy(kid+'->'+domain_id)}}}]->(d);")
            pat_id = f"pattern:{pattern}"
            out.append(f"MERGE (p:Concept {{id:{cy(pat_id)}}}) SET p.name={cy(pattern.replace('_',' ').title())}, p.concept_kind='pattern';")
            out.append(f"MATCH (n:{label} {{id:{cy(kid)}}}), (p:Concept {{id:{cy(pat_id)}}}) MERGE (n)-[:INSTANCE_OF_PATTERN {{id:{cy(kid+'->'+pat_id)}}}]->(p);")
            for aid in used:
                stats["attribute_links"] += 1
                rel = "USES_ATTRIBUTE" if label == "Metric" else "APPLIES_TO"
                out.append(f"MATCH (n:{label} {{id:{cy(kid)}}}), (a:LogicalAttribute {{id:{cy(aid)}}}) MERGE (n)-[:{rel} {{id:{cy(kid+'->'+aid)}}}]->(a);")
            if label == "Rule":
                output_id = f"concept:{db}:rule-output:{k['id']}"
                out.append(f"MERGE (c:Concept {{id:{cy(output_id)}}}) SET c.name={cy(k['knowledge'])}, c.concept_kind='rule_output', c.domain={cy(db)};")
                out.append(f"MATCH (r:Rule {{id:{cy(kid)}}}), (c:Concept {{id:{cy(output_id)}}}) MERGE (r)-[:PRODUCES {{id:{cy(kid+'->'+output_id)}}}]->(c);")
                # Entity CLASSIFIES/APPLIES_TO is derived only when referenced attributes share one entity.
                ents = sorted(set(a.rsplit(":", 1)[0].replace("attribute:", "entity:", 1) for a in used))
                if len(ents) == 1:
                    eid = ents[0]
                    out.append(f"MATCH (r:Rule {{id:{cy(kid)}}}), (e:LogicalEntity {{id:{cy(eid)}}}) MERGE (r)-[:CLASSIFIES {{id:{cy(kid+'->'+eid)}}}]->(e);")
            elif label == "Metric":
                ents = sorted(set(a.rsplit(":", 1)[0].replace("attribute:", "entity:", 1) for a in used))
                if len(ents) == 1:
                    eid = ents[0]
                    out.append(f"MATCH (m:Metric {{id:{cy(kid)}}}), (e:LogicalEntity {{id:{cy(eid)}}}) MERGE (m)-[:APPLIES_TO {{id:{cy(kid+'->'+eid)}}}]->(e);")

        for k in knowledge:
            children = k.get("children_knowledge", -1)
            if children in (-1, None): continue
            if not isinstance(children, list): children = [children]
            for child in children:
                if child not in node_ids: continue
                stats["dependencies"] += 1
                src, dst = node_ids[k["id"]], node_ids[child]
                out.append(f"MATCH (a {{id:{cy(src)}}}), (b {{id:{cy(dst)}}}) MERGE (a)-[:DEPENDS_ON {{id:{cy(src+'->'+dst)}}}]->(b);")
        out.append("")

    out.append("MATCH (n) WHERE n:Concept OR n:LogicalEntity OR n:LogicalAttribute OR n:Metric OR n:Rule OR n:PhysicalSchemaItem SET n.kg_version='v1', n.dataset_id='bird-interact-lite';")
    out.insert(2, "// " + json.dumps(stats, sort_keys=True))
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text("\n".join(out) + "\n")
    print(json.dumps(stats, indent=2, sort_keys=True))


if __name__ == "__main__":
    main()
