#!/usr/bin/env python3
"""Generate an idempotent Neo4j Cypher mapping for the BIRD-Interact KB.

This is deliberately not task-centric.  It consumes only database schemas,
column documentation and *_kb.jsonl files.  The generated graph preserves raw
assertions and promotes only deterministic extractions to structured nodes.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import re
from pathlib import Path


CREATE_TABLE = re.compile(r'CREATE TABLE\s+"?([^"\s(]+)"?\s*\((.*?)\n\);', re.I | re.S)
FOREIGN_KEY = re.compile(
    r'FOREIGN KEY\s*\(([^)]+)\)\s*REFERENCES\s+"?([^"\s(]+)"?\s*\(([^)]+)\)', re.I
)
PRIMARY_KEY = re.compile(r'PRIMARY KEY\s*\(([^)]+)\)', re.I)
DTYPE = re.compile(r'Data type:\s*([^\.]+)', re.I)
FULL_NAME = re.compile(r"Full name:\s*['\"]([^'\"]+)['\"]", re.I)
CATEGORIES = re.compile(r'Possible categories:\s*([^\.]+)', re.I)
UNIT_PARENS = re.compile(r'\((°C|°F|%|[A-Za-z]+/[A-Za-z]+|[A-Za-z]+)\)')
IDENT = re.compile(r'\\text\{([A-Za-z][A-Za-z0-9_]*)\}|\b([A-Z][A-Za-z0-9_]{2,})\b')


def norm(value: str) -> str:
    return re.sub(r'[^a-z0-9]+', '_', value.lower()).strip('_')


def q(value) -> str:
    if value is None:
        return 'null'
    if isinstance(value, bool):
        return 'true' if value else 'false'
    if isinstance(value, (int, float)):
        return str(value)
    return json.dumps(str(value), ensure_ascii=False)


def props(values: dict) -> str:
    return '{' + ', '.join(f'{k}: {q(v)}' for k, v in values.items() if v is not None) + '}'


def split_columns(raw: str) -> list[str]:
    return [x.strip().strip('"').lower() for x in raw.split(',')]


def parse_schema(path: Path):
    text = path.read_text(errors='replace')
    tables, fks = [], []
    for match in CREATE_TABLE.finditer(text):
        table, body = match.group(1).lower(), match.group(2)
        pk = set()
        pm = PRIMARY_KEY.search(body)
        if pm:
            pk.update(split_columns(pm.group(1)))
        columns = []
        for line in body.splitlines():
            s = line.strip().rstrip(',')
            if not s or re.match(r'(PRIMARY|FOREIGN|UNIQUE|CONSTRAINT|CHECK)\b', s, re.I):
                continue
            cm = re.match(r'"?([^"\s]+)"?\s+(.+)$', s)
            if cm:
                col, tail = cm.group(1).lower(), cm.group(2)
                dtype = re.split(r'\s+(?:NOT\s+NULL|NULL|DEFAULT|PRIMARY|REFERENCES|CHECK)\b', tail, maxsplit=1, flags=re.I)[0]
                columns.append({'name': col, 'data_type': dtype.strip(), 'nullable': not bool(re.search(r'NOT\s+NULL', tail, re.I)), 'primary_key': col in pk})
        for fm in FOREIGN_KEY.finditer(body):
            for local, remote in zip(split_columns(fm.group(1)), split_columns(fm.group(3))):
                fks.append((table, local, fm.group(2).lower(), remote))
        tables.append((table, columns))
    return tables, fks


def source_id(path: Path, root: Path) -> tuple[str, str, str]:
    rel = path.relative_to(root).as_posix()
    digest = hashlib.sha256(path.read_bytes()).hexdigest()
    return f'source:{rel}', rel, digest


def rule_shape(text: str) -> str:
    low = text.lower()
    if any(x in low for x in ('current_date', 'current_timestamp', 'days since', 'deadline', 'overdue')):
        return 'TemporalRule'
    if ('<' in text or '>' in text) and any(x in low for x in ('low', 'medium', 'high', 'category', 'classified')):
        return 'ClassificationRule'
    if '<' in text or '>' in text or ' threshold' in low:
        return 'ThresholdRule'
    if any(x in low for x in ('eligible', 'considered', 'qualifies', 'requires')):
        return 'EligibilityRule'
    return 'OpaqueRule'


def expression_kind(text: str) -> str:
    if any(x in text for x in ('=', '\\frac', '\\times', '+', '*', '/')):
        return 'Formula'
    return 'OpaqueExpression'


def emit(root: Path, output: Path):
    lines = [
        '// Generated by generate_mapping.py; do not hand edit.',
        '// Neo4j 5.x; rerunning is safe because identities use MERGE.',
        'CREATE CONSTRAINT v2_kg_node_id IF NOT EXISTS FOR (n:KGNode) REQUIRE n.id IS UNIQUE;',
        'CREATE INDEX v2_concept_name IF NOT EXISTS FOR (n:Concept) ON (n.name);',
        'CREATE INDEX v2_knowledge_name IF NOT EXISTS FOR (n:Knowledge) ON (n.name);',
        'CREATE INDEX v2_physical_lookup IF NOT EXISTS FOR (n:PhysicalSchemaItem) ON (n.database, n.table, n.name);',
        '',
    ]
    dataset_id = 'dataset:bird-interact-lite'
    version_id = 'version:bird-interact-lite:kg-v2:local-snapshot'
    lines += [
        f'MERGE (d:KGNode:Dataset {props({"id": dataset_id})}) SET d.name = "BIRD-Interact Lite";',
        f'MERGE (v:KGNode:Version {props({"id": version_id})}) SET v.name = "local-snapshot", v.kg_version = "v2", v.dataset_id = {q(dataset_id)};',
        f'MATCH (d:KGNode {{id:{q(dataset_id)}}}), (v:KGNode {{id:{q(version_id)}}}) MERGE (d)-[:HAS_VERSION]->(v);',
    ]

    docs_by_db, schemas_by_db = {}, {}
    for db_dir in sorted(p for p in root.iterdir() if p.is_dir()):
        db = db_dir.name
        docs_path = db_dir / f'{db}_column_meaning_base.json'
        schema_path = db_dir / f'{db}_schema.txt'
        kb_path = db_dir / f'{db}_kb.jsonl'
        if not kb_path.exists():
            continue
        domain_id = f'concept:domain:{db}'
        lines.append(f'MERGE (n:KGNode:Concept:Domain {props({"id": domain_id})}) SET n.name={q(db)}, n.concept_kind="domain";')

        docs = json.loads(docs_path.read_text()) if docs_path.exists() else {}
        docs_by_db[db] = docs
        tables, fks = parse_schema(schema_path) if schema_path.exists() else ([], [])
        schemas_by_db[db] = (tables, fks)

        # Provenance sources
        for path, kind in ((schema_path, 'ddl_and_samples'), (docs_path, 'column_documentation'), (kb_path, 'knowledge_base')):
            if not path.exists():
                continue
            sid, rel, digest = source_id(path, root)
            lines.append(f'MERGE (s:KGNode:ProvenanceSource {props({"id": sid})}) SET s.path={q(rel)}, s.sha256={q(digest)}, s.source_kind={q(kind)};')
            lines.append(f'MATCH (s:KGNode {{id:{q(sid)}}}), (v:KGNode {{id:{q(version_id)}}}) MERGE (s)-[:PART_OF_VERSION]->(v);')

        doc_lookup = {}
        for key, description in docs.items():
            parts = key.split('|')
            if len(parts) < 3:
                continue
            _, table_display, *column_parts = parts
            table, column = table_display.lower(), '|'.join(column_parts)
            # Some JSONB columns use a nested documentation object.  Preserve
            # it losslessly as JSON; path-level promotion is intentionally a
            # later, confidence-gated transformation.
            if not isinstance(description, str):
                description = json.dumps(description, ensure_ascii=False, sort_keys=True)
            doc_lookup[(table, column.lower())] = description

        for table, columns in tables:
            entity_id = f'entity:{db}:{table}'
            ptable_id = f'physical:{db}:table:{table}'
            lines.append(f'MERGE (e:KGNode:LogicalEntity {props({"id": entity_id})}) SET e.name={q(table)}, e.database={q(db)};')
            lines.append(f'MERGE (p:KGNode:PhysicalSchemaItem:PhysicalTable {props({"id": ptable_id})}) SET p.name={q(table)}, p.database={q(db)}, p.table={q(table)};')
            lines.append(f'MATCH (p:KGNode {{id:{q(ptable_id)}}}), (e:KGNode {{id:{q(entity_id)}}}) MERGE (p)-[:IMPLEMENTS]->(e);')
            lines.append(f'MATCH (e:KGNode {{id:{q(entity_id)}}}), (d:KGNode {{id:{q(domain_id)}}}) MERGE (e)-[:VALID_IN_DOMAIN]->(d);')
            for col in columns:
                cname = col['name']
                desc = doc_lookup.get((table, cname), '')
                full = FULL_NAME.search(desc)
                attr_name = full.group(1) if full else cname
                attr_id = f'attribute:{db}:{table}:{cname}'
                pcol_id = f'physical:{db}:column:{table}:{cname}'
                dtype_id = f'datatype:{norm(col["data_type"])}'
                lines.append(f'MERGE (a:KGNode:LogicalAttribute {props({"id": attr_id})}) SET a.name={q(attr_name)}, a.database={q(db)}, a.table={q(table)}, a.description={q(desc) if desc else "null"};')
                lines.append(f'MERGE (p:KGNode:PhysicalSchemaItem:PhysicalColumn {props({"id": pcol_id})}) SET p.name={q(cname)}, p.database={q(db)}, p.table={q(table)}, p.data_type={q(col["data_type"])}, p.nullable={q(col["nullable"])}, p.primary_key={q(col["primary_key"])};')
                lines.append(f'MERGE (t:KGNode:Datatype {props({"id": dtype_id})}) SET t.name={q(col["data_type"])};')
                lines.append(f'MATCH (e:KGNode {{id:{q(entity_id)}}}), (a:KGNode {{id:{q(attr_id)}}}) MERGE (e)-[:HAS_ATTRIBUTE]->(a);')
                lines.append(f'MATCH (p:KGNode {{id:{q(pcol_id)}}}), (a:KGNode {{id:{q(attr_id)}}}) MERGE (p)-[:IMPLEMENTS]->(a);')
                lines.append(f'MATCH (p:KGNode {{id:{q(pcol_id)}}}), (t:KGNode {{id:{q(dtype_id)}}}) MERGE (p)-[:HAS_DATATYPE]->(t);')
                if desc:
                    sid, _, _ = source_id(docs_path, root)
                    aid = f'assertion:column-doc:{db}:{table}:{cname}'
                    lines.append(f'MERGE (x:KGNode:Assertion {props({"id": aid})}) SET x.assertion_kind="column_documentation", x.raw_text={q(desc)}, x.status="asserted", x.confidence=0.80;')
                    lines.append(f'MATCH (x:KGNode {{id:{q(aid)}}}), (a:KGNode {{id:{q(attr_id)}}}) MERGE (x)-[:ASSERTS_ABOUT]->(a);')
                    lines.append(f'MATCH (x:KGNode {{id:{q(aid)}}}), (s:KGNode {{id:{q(sid)}}}) MERGE (x)-[:SUPPORTED_BY]->(s);')
                    cm = CATEGORIES.search(desc)
                    if cm:
                        for literal in [v.strip().strip("'\"") for v in cm.group(1).split(',') if v.strip()]:
                            lid = f'literal:{db}:{table}:{cname}:{norm(literal)}'
                            lines.append(f'MERGE (l:KGNode:Literal:CategoryValue {props({"id": lid})}) SET l.name={q(literal)}, l.value={q(literal)};')
                            lines.append(f'MATCH (a:KGNode {{id:{q(attr_id)}}}), (l:KGNode {{id:{q(lid)}}}) MERGE (a)-[:ALLOWS_VALUE {{evidence:"documentation"}}]->(l);')
                    um = UNIT_PARENS.search(attr_name)
                    if um:
                        unit = um.group(1)
                        uid = f'unit:{norm(unit)}'
                        lines.append(f'MERGE (u:KGNode:Unit {props({"id": uid})}) SET u.name={q(unit)};')
                        lines.append(f'MATCH (a:KGNode {{id:{q(attr_id)}}}), (u:KGNode {{id:{q(uid)}}}) MERGE (a)-[:MEASURED_IN]->(u);')

        for table, local, target_table, remote in fks:
            left = f'physical:{db}:column:{table}:{local}'
            right = f'physical:{db}:column:{target_table}:{remote}'
            left_table = f'physical:{db}:table:{table}'
            right_table = f'physical:{db}:table:{target_table}'
            jid = f'join:{db}:{table}.{local}:{target_table}.{remote}'
            lines.append(f'MERGE (j:KGNode:JoinCondition {props({"id": jid})}) SET j.operator="=", j.database={q(db)}, j.expression={q(table+"."+local+" = "+target_table+"."+remote)}, j.evidence="DDL";')
            lines.append(f'MATCH (l:KGNode {{id:{q(left)}}}), (r:KGNode {{id:{q(right)}}}), (j:KGNode {{id:{q(jid)}}}) MERGE (l)-[:JOINABLE_VIA]->(j) MERGE (j)-[:JOINS_TO]->(r);')
            lines.append(f'MATCH (l:KGNode {{id:{q(left_table)}}}), (r:KGNode {{id:{q(right_table)}}}), (j:KGNode {{id:{q(jid)}}}) MERGE (l)-[:JOINABLE_VIA]->(j) MERGE (j)-[:JOINS_TO]->(r);')

        column_tokens = {}
        for table, columns in tables:
            for col in columns:
                column_tokens.setdefault(col['name'].lower(), []).append((table, col['name']))

        knowledge = []
        for line_no, raw in enumerate(kb_path.read_text().splitlines(), 1):
            if not raw.strip():
                continue
            item = json.loads(raw)
            knowledge.append(item)
            kid = f'knowledge:{db}:{item["id"]}'
            kind = {'calculation_knowledge': 'Metric', 'domain_knowledge': 'Rule', 'value_illustration': 'Concept'}.get(item.get('type'), 'Knowledge')
            extra = ':Knowledge:' + kind
            if kind == 'Rule':
                extra += ':' + rule_shape(item.get('definition', ''))
            lines.append(f'MERGE (k:KGNode{extra} {props({"id": kid})}) SET k.name={q(item.get("knowledge"))}, k.description={q(item.get("description"))}, k.raw_definition={q(item.get("definition"))}, k.knowledge_type={q(item.get("type"))}, k.database={q(db)}, k.source_line={line_no};')
            lines.append(f'MATCH (k:KGNode {{id:{q(kid)}}}), (d:KGNode {{id:{q(domain_id)}}}) MERGE (k)-[:VALID_IN_DOMAIN]->(d);')
            sid, _, _ = source_id(kb_path, root)
            aid = f'assertion:kb:{db}:{item["id"]}'
            lines.append(f'MERGE (x:KGNode:Assertion {props({"id": aid})}) SET x.assertion_kind="knowledge_definition", x.raw_text={q(item.get("definition"))}, x.status="asserted", x.confidence=0.90, x.source_line={line_no};')
            lines.append(f'MATCH (x:KGNode {{id:{q(aid)}}}), (k:KGNode {{id:{q(kid)}}}) MERGE (x)-[:ASSERTS_ABOUT]->(k);')
            lines.append(f'MATCH (x:KGNode {{id:{q(aid)}}}), (s:KGNode {{id:{q(sid)}}}) MERGE (x)-[:SUPPORTED_BY]->(s);')
            definition = item.get('definition', '') or ''
            if kind in ('Metric', 'Rule'):
                eid = f'expression:{db}:{item["id"]}'
                ekind = expression_kind(definition)
                lines.append(f'MERGE (e:KGNode:Expression:{ekind} {props({"id": eid})}) SET e.raw_expression={q(definition)}, e.parse_status="raw", e.language="natural-language-and-latex";')
                lines.append(f'MATCH (k:KGNode {{id:{q(kid)}}}), (e:KGNode {{id:{q(eid)}}}) MERGE (k)-[:DEFINED_BY]->(e);')
                grain_id = f'grain:{db}:unspecified'
                aggregation_id = f'aggregation:{db}:{item["id"]}:unspecified'
                lines.append(f'MERGE (g:KGNode:Grain {props({"id": grain_id})}) SET g.name="unspecified", g.status="unresolved";')
                lines.append(f'MATCH (k:KGNode {{id:{q(kid)}}}), (g:KGNode {{id:{q(grain_id)}}}) MERGE (k)-[:EVALUATED_AT_GRAIN]->(g);')
                lines.append(f'MERGE (a:KGNode:AggregationPolicy {props({"id": aggregation_id})}) SET a.name="unspecified", a.status="unresolved";')
                lines.append(f'MATCH (k:KGNode {{id:{q(kid)}}}), (a:KGNode {{id:{q(aggregation_id)}}}) MERGE (k)-[:HAS_AGGREGATION_POLICY]->(a);')
                if any(x in definition.lower() for x in ('current_date', 'current_timestamp', 'days since', 'deadline', 'overdue')):
                    tid = f'time-window:{db}:{item["id"]}'
                    lines.append(f'MERGE (t:KGNode:TimeWindow {props({"id": tid})}) SET t.raw_definition={q(definition)}, t.parse_status="raw", t.evaluation_time_required=true;')
                    lines.append(f'MATCH (k:KGNode {{id:{q(kid)}}}), (t:KGNode {{id:{q(tid)}}}) MERGE (k)-[:HAS_TIME_WINDOW]->(t);')
            tokens = {a or b for a, b in IDENT.findall(definition)}
            for token in sorted(tokens, key=str.lower):
                hits = column_tokens.get(token.lower(), [])
                if len(hits) == 1:
                    table, col = hits[0]
                    attr_id = f'attribute:{db}:{table}:{col}'
                    lines.append(f'MATCH (k:KGNode {{id:{q(kid)}}}), (a:KGNode {{id:{q(attr_id)}}}) MERGE (k)-[:USES_ATTRIBUTE {{mapping_method:"exact_identifier", confidence:0.98}}]->(a);')

        for item in knowledge:
            child = item.get('children_knowledge', -1)
            children = child if isinstance(child, list) else ([] if child in (-1, None) else [child])
            for dep in children:
                lines.append(f'MATCH (a:KGNode {{id:{q(f"knowledge:{db}:{item["id"]}")}}}), (b:KGNode {{id:{q(f"knowledge:{db}:{dep}")}}}) MERGE (a)-[:DEPENDS_ON {{evidence:"children_knowledge"}}]->(b);')

    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text('\n'.join(lines) + '\n')
    print(f'wrote {output} ({len(lines):,} Cypher statements)')


if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('--dataset', type=Path, default=Path(__file__).resolve().parents[2] / 'BIRD-Interact-Claude' / 'bird-interact-lite')
    parser.add_argument('--output', type=Path, default=Path(__file__).with_name('mapping.cypher'))
    args = parser.parse_args()
    emit(args.dataset.resolve(), args.output.resolve())
